apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- donation-db-init.yaml

namespace: solidary
images:
- name: donation-service
  newName: 158176292469.dkr.ecr.us-east-1.amazonaws.com/solidary-tech-donation-service
  newTag: v1.0.0-69ff84e
