apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: solidary
spec:
  selector:
    app: donation-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP