apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
namespace: solidary
images:
- name: volunteer-service
  newName: 158176292469.dkr.ecr.us-east-1.amazonaws.com/solidary-tech-volunteer-service
  newTag: v1.0.0-dc25cb9
