apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-service
  namespace: solidary
  labels:
    app: ngo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngo-service
  template:
    metadata:
      labels:
        app: ngo-service
    spec:
      containers:
      - name: ngo-service
        # Nome curto - o Kustomize substitui pelo path completo do ECR + tag do commit
        image: ngo-service
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: ngo-config
        - secretRef:
            name: ngo-secret

        # ---> ENV PARA O OPENTELEMETRY <---
        env:
        - name: OTEL_SERVICE_NAME
          value: "ngo-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observabilidade.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=production,service.version=1.0.0"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20
